"""initial schema

Revision ID: 0de7596a9530
Revises: 
Create Date: 2026-05-24 17:32:20.634928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0de7596a9530'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archive_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_category_slug'), ['slug'], unique=True)

    op.create_table('course',
    sa.Column('course_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='coursestatus'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_course_code'), ['course_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_course_slug'), ['slug'], unique=True)

    op.create_table('course_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_category_slug'), ['slug'], unique=True)

    op.create_table('payment_method',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_method_code'), ['code'], unique=True)

    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'teacher', 'student', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('archive',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumbnail_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='archivestatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('archive_category_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['archive_category_id'], ['archive_category.id'], ),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_archive_archive_category_id'), ['archive_category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_archive_slug'), ['slug'], unique=True)

    op.create_table('course_category_link',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_category_id'], ['course_category.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'course_category_id')
    )
    op.create_table('section',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_section_course_id'), ['course_id'], unique=False)

    op.create_table('student',
    sa.Column('student_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'graduated', name='studentstatus'), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_student_code'), ['student_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_user_id'), ['user_id'], unique=True)

    op.create_table('enrollment',
    sa.Column('status', sa.Enum('active', 'cancelled', 'completed', name='enrollmentstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_enrollment_student_course')
    )
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollment_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollment_student_id'), ['student_id'], unique=False)

    op.create_table('lesson',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('video_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_preview', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_section_id'), ['section_id'], unique=False)

    op.create_table('order',
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', 'refunded', 'cancelled', name='paymentstatus'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('provider_txn_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_method.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_order_code'), ['order_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_payment_method_id'), ['payment_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_student_id'), ['student_id'], unique=False)

    op.create_table('lesson_progress',
    sa.Column('seconds_watched', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_lesson_progress_student_lesson')
    )
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lesson_progress_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lesson_progress_student_id'), ['student_id'], unique=False)

    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'course_id', name='uq_order_item_order_course')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_item_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_course_id'))

    op.drop_table('order_item')
    with op.batch_alter_table('lesson_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_progress_lesson_id'))

    op.drop_table('lesson_progress')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_student_id'))
        batch_op.drop_index(batch_op.f('ix_order_payment_status'))
        batch_op.drop_index(batch_op.f('ix_order_payment_method_id'))
        batch_op.drop_index(batch_op.f('ix_order_order_code'))

    op.drop_table('order')
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lesson_section_id'))
        batch_op.drop_index(batch_op.f('ix_lesson_course_id'))

    op.drop_table('lesson')
    with op.batch_alter_table('enrollment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollment_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollment_course_id'))

    op.drop_table('enrollment')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_student_code'))

    op.drop_table('student')
    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_section_course_id'))

    op.drop_table('section')
    op.drop_table('course_category_link')
    with op.batch_alter_table('archive', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_slug'))
        batch_op.drop_index(batch_op.f('ix_archive_author_id'))
        batch_op.drop_index(batch_op.f('ix_archive_archive_category_id'))

    op.drop_table('archive')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_method_code'))

    op.drop_table('payment_method')
    with op.batch_alter_table('course_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_category_slug'))

    op.drop_table('course_category')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_slug'))
        batch_op.drop_index(batch_op.f('ix_course_course_code'))

    op.drop_table('course')
    with op.batch_alter_table('archive_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_archive_category_slug'))

    op.drop_table('archive_category')
    # ### end Alembic commands ###
