"""add coupon review certificate + order pricing

Revision ID: 1f1873b73dd4
Revises: 0de7596a9530
Create Date: 2026-05-24 21:45:22.455290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f1873b73dd4'
down_revision: Union[str, Sequence[str], None] = '0de7596a9530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('discount_type', sa.Enum('percent', 'fixed', name='coupontype'), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupon_code'), ['code'], unique=True)

    op.create_table('certificate',
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_certificate_student_course')
    )
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificate_certificate_code'), ['certificate_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificate_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificate_student_id'), ['student_id'], unique=False)

    op.create_table('review',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_review_student_course')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtotal_amount', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('discount_amount', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('coupon_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_foreign_key('fk_order_coupon_id', 'coupon', ['coupon_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_coupon_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_coupon_id'))
        batch_op.drop_column('coupon_id')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('subtotal_amount')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_student_id'))
        batch_op.drop_index(batch_op.f('ix_review_course_id'))

    op.drop_table('review')
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificate_student_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_course_id'))
        batch_op.drop_index(batch_op.f('ix_certificate_certificate_code'))

    op.drop_table('certificate')
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupon_code'))

    op.drop_table('coupon')
    # ### end Alembic commands ###
